spring:
  application:
    name: demo-consumer # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

server:
  port: 28080 # 服务器端口。默认为 8080

logging:
  level:
    # 指定日志级别设定 接口
    com.unionpay.feign.feigndemo.consumer.feign: DEBUG   # debug 级别日志

feign:
  # Feign 客户端配置，对应 FeignClientProperties 配置属性类
  client:
    # config 配置项是 Map 类型。key 为 Feign 客户端的名字，value 为 FeignClientConfiguration 对象
    config:
      # 全局级别配置
      default:
        logger-level: BASIC   # 只打印基本信息，包括请求方法、请求地址、响应状态码、请求时长
      # 客户端级别配置
      demo-provider:  # 注释掉之后以 全局为准
        logger-level: FULL   # 打印完整信息，包括请求和响应的所有信息。
