server:
  port: 8888    # 访问 http://127.0.0.1:8888 查看返回权重

spring:
  application:
    name: gateway-application

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: user-service-prod
          uri: https://blog.yarwen.com
          predicates:
            - Path=/**
            # 设置不同的权重条件。其中，第一个参数为权重分组，需要配置成相同，一般和服务名相同即可；第二个参数为权重比例。
            - Weight=user-service, 50           # 流量权重
        - id: user-service-canary
          uri: https://www.oschina.net
          predicates:
            - Path=/**
            - Weight=user-service, 50            # 流量权重
