server:
  port: 8888  # http://127.0.0.1:8888/oschina

spring:
  application:
    name: zuul-application

# Zuul 配置项，对应 ZuulProperties 配置类
zuul:
  servlet-path: / # ZuulServlet 匹配的路径，默认为 /zuul
  # 路由配置项，对应 ZuulRoute Map
  routes:
    route_archives:
      path: /archives/**
      url: https://blog.yarwen.com
    route_oschina:
      path: /oschina/**
      url: https://www.oschina.net