spring:
  application:
    name: demo-consumer # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

server:
  port: 28080 # 服务器端口。默认为 8080


# 使用方法
# 通过在配置文件中，添加 {clientName}.ribbon.{key}={value} 配置项，
# 设置指定名字的 Ribbon 客户端的指定属性的值。实现 Ribbon 客户端级别的自定义配置。

# 设置 Ribbon 客户端的自定义配置
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
demo-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则全类名
